config/routes.rb
Rails.application.routes.draw do
  root to: 'campaigns#index'

  resources :campaigns, only: %i[index show] do
    resources :ad_codes, only: %i[show index] do
      get 'against/:other_index', to: 'ad_codes#against', as: :against
      get 'hosts'
      get 'timeline'

      resources :values, only: :show
    end
  end

  get '/adverts/decode-a-link'
  resources :adverts, only: %i[show index]

  resources :decodings, only: %i[create show]

  resources :searches, only: %i[new create]

  ##
  # Redirects; this once only did one campaign - Trump's, and now
  # we must preserve URLs in spreadsheets and so on.
  get '/utm_campaign_values', to: redirect('/campaigns/trump/ad_codes')
  get '/utm_campaign_values/:id', to: redirect('/campaigns/trump/ad_codes/%{id}')
  # Between is now default view, or timeline, on ad_codes. Use path: to preserve query string
  get '/utm_campaign_values/:id/between', to: redirect(path: '/campaigns/trump/ad_codes/%{id}')
  get '/utm_campaign_values/:id/against/:other_id', to: redirect('/campaigns/trump/ad_codes/%{id}/against/%{other_id}/')
  get '/utm_campaign_values/:id/hosts', to: redirect('/campaigns/trump/ad_codes/%{id}/hosts')

  resources :hosts, only: :index do
    get 'adverts'
  end
end

app/models/ad_code.rb
class AdCode < ApplicationRecord
  belongs_to :campaign

  has_many :ad_code_value_summaries

  def full_name
    "#{name} (utm#{index})"
  end

  def to_s
    name
  end

  def to_param
    index
  end
end

app/controllers/ad_codes_controller.rb
class AdCodesController < ApplicationController
  before_action :set_campaign
  before_action :set_ad_code, except: :index

  breadcrumb -> { @campaign.name }, -> { campaign_path(@campaign.slug) }, match: :exclusive
  breadcrumb 'Ad codes', -> { campaign_ad_codes_path(@campaign) }, match: :exclusive

  def index
    @ad_codes = ad_codes_with_sort.group_by(&:name)
  end

  def show
    @ad_codes = ad_codes_with_sort.where(campaign_id: @campaign.id, index: params[:id])
    breadcrumb @ad_code.full_name, request.path
  end

  DENSITY_ROWHEIGHTS = {
    'dense' => 32,
    'spacious' => 42
  }.freeze

  def timeline
    @values = ValueDailySummary.between(@campaign, @ad_code.index, start, finish, dimension: dimension)
    @options = {
      rowHeight: DENSITY_ROWHEIGHTS[params[:density] || 'spacious'],
      svgClass: "utm#{@ad_code.index}",
      linkRowUsing: 'pathToAdCodeValue'
    }

    breadcrumb "#{@ad_code.full_name} / Timeline", request.path
  end

  def against
    @ad_code2 = AdCode.where(campaign: @campaign, index: params[:other_index]).first

    @table = AdCodeValueUsage::ContingencyTable.new(@campaign.id, @ad_code.index, @ad_code2.index)

    breadcrumb @ad_code.full_name, campaign_ad_code_path(@campaign, params[:ad_code_id]), match: :exclusive
    breadcrumb "against / #{@ad_code2.full_name}", request.path
  end

  def hosts
    @table = Host::ContingencyTable.new(AdCodeValueUsage.by_host(@campaign.id, @ad_code.index))

    breadcrumb @ad_code.full_name, campaign_ad_code_path(campaign_id: @campaign.slug, id: @ad_code.index), match: :exclusive
    breadcrumb 'Hosts', request.path
  end

  private

  def ad_codes_with_sort
    ad_codes = @campaign.ad_code_value_summaries.with_value_names
    if params[:sort] == 'spend'
      ad_codes.order('COALESCE(approximate_spend, 0) DESC')
    elsif params[:sort] == 'cpm'
      ad_codes.order('COALESCE(approximate_cpm, 0) DESC')
    else
      ad_codes.order(count: :desc)
    end
  end

  def set_ad_code
    @ad_code = AdCode.where(campaign: @campaign, index: params[:ad_code_id] || params[:id]).first
    @other_ad_codes = AdCode.where('ad_codes.campaign_id = ? AND ad_codes.index <> ?', @campaign.id, @ad_code.index).order(quality: :desc)
  end

  def set_campaign
    @campaign ||= Campaign.where(slug: campaign_slug).first
  end

  def campaign_slug
    params[:campaign_id]
  end

  def start
    @start ||= params[:start] ? Date.parse(params[:start]) : Date.today - 30
  end

  def finish
    @finish ||= params[:end] ? Date.parse(params[:end]) : Date.today
  end

  def dimension
    params[:dimension].presence || 'count'
  end
end

app/helpers/ad_codes_helper.rb
module AdCodesHelper
  def new_ad_code?(ad_code, days = 2)
    threshold = Date.today - days.to_i
    ad_code.first_used > threshold
  end

  def nav_link(action)
    bootstrap_class = "nav-link #{action.to_s == params[:action].to_s ? 'active' : ''}"

    case action
    when :show
      link_to 'Values', campaign_ad_code_path(@campaign, id: @ad_code.index), class: bootstrap_class
    when :timeline
      link_to 'Timeline', campaign_ad_code_timeline_path(@campaign, ad_code_id: @ad_code.index), class: bootstrap_class
    when :against
      link_to 'Show against', '#',
              class: bootstrap_class + ' dropdown-toggle',
              data: { toggle: 'dropdown' },
              role: 'button',
              aria: { haspopup: 'true', expanded: 'false' }
    when :hosts
      link_to 'Hosts', campaign_ad_code_hosts_path(@campaign, ad_code_id: @ad_code.index), class: bootstrap_class
    else
      raise ArgumentError("#{action} not a tab")
    end
  end

  def timeline_ranges
    {
      all_time: Date.new(2020, 5, 1),
      last_30_days: 30.days.ago.to_date,
      last_7_days: 7.days.ago.to_date
    }
  end

  def timeline_range_links
    tag.ul class: 'nav nav-pills' do
      timeline_ranges.map do |label, start_date|
        active = params[:range] == label.to_s || params[:range].nil? && label == :last_30_days
        tag.li class: 'nav-item' do
          link_to label.to_s.titleize,
            request.query_parameters.merge(start: start_date.iso8601, range: label),
                  class: "nav-link #{'active' if active }"
        end
      end.join.html_safe
    end
  end
end

app/views/ad_codes/_ad_codes_list.html.erb
<% top ||= 9999 %>

<ul class="percentage-list">
  <% values.take(top).each do |value| %>
    <li>
      <span class="percentage utm<%= index %>" style="width: <%= value.percentage %>%"></span>

      <span class="content">
        <%= link_to campaign_ad_code_value_path(@campaign, value.index, value.value) do %>
          <span class="<%= badge_class(value.value) %>"><%= value.value %></span>
          <% if value.value_name %>
            <%= value.value_name %>
          <% end %>
        <% end %>

        <small class="text-right">
          <%= link_to "#{value.percentage}% of adverts",
            adverts_path("with_utm_values[#{value.index}]" => "#{value.value}"), class: "ml-1" %>
          <span class="ml-1">
            <%= round_dollars(value.approximate_spend) %>
          </span>

          <% if value.approximate_cpm.present? %>
            <span class="text-muted">
              (<%= round_dollars(value.approximate_cpm) %> <abbr title="Cost per mille" class="initialism">CPM</abbr>)
            </span>
          <% end %>
        </small>
      </span>

      <% if new_ad_code?(value, params[:new] || 2) %>
        <span class="badge badge-success">New</span>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/ad_codes/_sort_links.html.erb
<div class="row mb-3">
  <div class="nav nav-pills">
    <span class="nav-item">
      <span class="nav-link text-muted">Sort by descending</span>
    </span>
  </div>
  <ul class="col nav nav-pills">
    <li class="nav-item">
      <%= link_to 'Count',
                  request.query_parameters.merge(sort: 'count'),
                  class: "nav-link #{'active' unless %w[spend cpm].include?(params[:sort]) }" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Spend',
        request.query_parameters.merge(sort: 'spend'),
        class: "nav-link #{'active' if params[:sort] == 'spend'}" %>
    </li>
    <li class="nav-item">
      <%= link_to 'CPM',
        request.query_parameters.merge(sort: 'cpm'),
        class: "nav-link #{'active' if params[:sort] == 'cpm'}" %>
    </li>
  </ul>
</div>
<hr>

app/views/ad_codes/_tabs.html.erb
<ul class="nav nav-tabs ad-code-nav">
  <li class="nav-item">
    <%= nav_link(:show) %>
  </li>
  <li class="nav-item">
    <%= nav_link(:timeline) %>
  </li>
  <li class="nav-item dropdown">
    <%= nav_link(:against) %>
    <div class="dropdown-menu">
      <% add_divider_at_quality_1 = true   %>
      <% @other_ad_codes.each do |ad_code| %>
        <% if ad_code.quality == 1 && add_divider_at_quality_1 %>
          <div class="dropdown-divider"></div>
          <% add_divider_at_quality_1 = false %>
        <% end %>

        <div class="dropdown-item">
          <%=
            link_to ad_code.name, campaign_ad_code_against_path(
              ad_code_id: @ad_code.index, other_index: ad_code.index
            ), class: "#{'text-muted' if ad_code.quality <= 1}"
          %>
          <small class="text-muted">utm<%= ad_code.index %></small>
        </div>
      <% end %>
    </div>
  </li>
  <li class="nav-item <%= 'na' %>">
    <%= nav_link :hosts %>
  </li>
</ul>

app/views/ad_codes/_timeline_density_dropdown.html.erb
<div class="btn-group">
  <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Density
  </button>
  <div class="dropdown-menu">
    <%= link_to 'Dense', request.query_parameters.merge(density: 'dense'), class: 'dropdown-item' %>
    <%= link_to 'Spacious', request.query_parameters.merge(density: 'spacious'), class: 'dropdown-item' %>
  </div>
</div>

app/views/ad_codes/against.html.erb
<%= render 'shared/breadcrumb' %>

<% content_for :title, "Adverts at all combinations of #{@ad_code.name} and #{@ad_code2.name}"  %>
<h1>Adverts at all combinations of <%= @ad_code.name %> and <%= @ad_code2.name %></h1>

<%= render 'tabs' %>

<table class="against table table-heading table-bordered">
  <thead class="thead-light">
  <tr>
    <th>
      <%=
        link_to 'Swap',
                campaign_ad_code_against_path(@campaign, @ad_code2.index, @ad_code.index),
                class: 'button'
      %>
    </th>
    <th colspan="99" style="text-align: center">
      <%= link_to campaign_ad_code_path(@campaign, @table.index1) do %>
        <%= @ad_code.name %>
        <small class="text-muted">utm<%= @ad_code.index %></small>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>
      <%= link_to campaign_ad_code_path(@campaign, @table.index2) do %>
        <%= @ad_code2.name %>
        <small class="text-muted">utm<%= @ad_code2.index %></small>
      <% end %>
    </th>
    <% @table.col_values.each do |col_value| %>
      <th>
        <%= link_to col_value, campaign_ad_code_value_path(@campaign, @ad_code, id: col_value) if col_value %>
      </th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% @table.to_a.each_with_index do |row, row_index| %>
    <tr>
      <th scope="row">
        <%= link_to @table.row_values[row_index], campaign_ad_code_value_path(@campaign, @ad_code2, id: @table.row_values[row_index]) %>
      </th>
      <% row.each_with_index do |value, col_index| %>
        <td>
          <% if value %>
            <%= link_to value,
              adverts_path(
                "with_utm_values[#{@table.index1}]" => @table.col_values[col_index],
                "with_utm_values[#{@table.index2}]" => @table.row_values[row_index]
              )
            %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/ad_codes/hosts.html.erb
<%= render 'shared/breadcrumb' %>

<% content_for :title, "#{@campaign.surname} | #{@ad_code.full_name} | Hosts" %>

<h1>
  Hosts for "<%= @ad_code.name %>"
  <small class="text-muted">utm<%= @ad_code.index %></small>
</h1>

<%= render 'tabs' %>

<table class="against table table-heading table-bordered">

  <thead class="thead-light">
  <tr>
    <th colspan="2" width="30%">
      Host
    </th>
    <% @table.col_values.each do |col_value| %>
      <th>
        <%=
          link_to col_value,
                  campaign_ad_code_value_path(@campaign, @ad_code.index, col_value) if col_value
        %>
      </th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% @table.to_a.each_with_index do |row, row_index| %>
    <% hostname = @table.row_values[row_index] %>
    <tr>
      <th scope="row">
        <%= hostname %>
      </th>
      <th scope="row">
        <span class="text-muted"><%= @table.row_by_hostname[hostname]&.purpose %></span>
      </th>
      <% row.each_with_index do |value, col_index| %>
        <td>
          <% if value %>
            <%= link_to value, adverts_path(
              "with_utm_values[#{@ad_code.index}]" => @table.col_values[col_index],
              'hostname' => hostname
            )
            %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>

</table>

app/views/ad_codes/index.html.erb
<%= render 'shared/breadcrumb' %>

<% top ||= 10 %>

<%= content_for :title, "#{@campaign.surname} | Ad codes and their values" %>
<h1>Ad codes and their values</h1>

<%= render 'sort_links' %>

<ul class="tag-list">
  <% @ad_codes.each_pair do |name, values| %>
    <li>
     <%=
       link_to name, "##{name.downcase.gsub(' ', '-')}",
         class: values.first.quality <= 1 ? 'text-muted' : '',
         data: { turbolinks: false }
     %>
    </li>
  <% end %>
</ul>

<% @ad_codes.each_pair do |name, values| %>
  <div class="a8-code">
    <a name="<%= name.downcase.gsub(' ', '-') %>"></a>
    <h2 class="heading">
      <%= link_to name, campaign_ad_code_path(@campaign, values.first.index, sort: params[:sort]) %>
      <small class="text-muted">utm<%= values.first.index %></small>
    </h2>

    <p><%= values.first.short_desc %></p>
    <hr>

    <h3 class="h5">
      <%= values.count %> values
      <% if values.count > 10 %>
        <small class="text-muted">
          – showing <%= top %>,
          <%= link_to 'see more', campaign_ad_code_path(@campaign, values.first.index) %>
        </small>
      <% end %>
    </h3>

    <%=
      render 'ad_codes_list',
      values: values,
      index: values.first.index,
      top: top
    %>
  </div>
<% end %>

app/views/ad_codes/show.html.erb
<%= render 'shared/breadcrumb' %>

<%= content_for :title, @ad_code.full_name %>

<h1>
  <%= @ad_code.name %>
  <small class="text-muted">
    <%= "utm#{@ad_code.index}" %>, <%= confidence_badge(@ad_code.confidence) %> confidence
  </small>
</h1>

<%= render 'ad_codes/tabs' %>

<%= render 'ad_codes/sort_links' %>

<%= markdown_to_html(@ad_code.description) %>

<h2>Values</h2>

<%= render 'ad_codes/ad_codes_list', values: @ad_codes, index: @ad_code.index %>

app/views/ad_codes/timeline.html.erb
<%= render 'shared/breadcrumb' %>

<% content_for :title, "#{@campaign.surname} | #{@ad_code.name} | Timeline" %>
<h1><%= @ad_code.name %> <small class="text-muted"><%= "utm#{@ad_code.index}" %></small></h1>

<%= render 'ad_codes/tabs' %>

<h2>Values between <%= @start %> and <%= @finish %> </h2>

<%= render 'shared/timeline_dimension_toolbar', show_density: true %>

<%= timeline(@values, @options) %>