config/routes.rb
Rails.application.routes.draw do
  root to: 'campaigns#index'

  resources :campaigns, only: %i[index show] do
    resources :ad_codes, only: %i[show index] do
      get 'against/:other_index', to: 'ad_codes#against', as: :against
      get 'hosts'
      get 'timeline'

      resources :values, only: :show
    end
  end

  get '/adverts/decode-a-link'
  resources :adverts, only: %i[show index]

  resources :decodings, only: %i[create show]

  resources :searches, only: %i[new create]

  ##
  # Redirects; this once only did one campaign - Trump's, and now
  # we must preserve URLs in spreadsheets and so on.
  get '/utm_campaign_values', to: redirect('/campaigns/trump/ad_codes')
  get '/utm_campaign_values/:id', to: redirect('/campaigns/trump/ad_codes/%{id}')
  # Between is now default view, or timeline, on ad_codes. Use path: to preserve query string
  get '/utm_campaign_values/:id/between', to: redirect(path: '/campaigns/trump/ad_codes/%{id}')
  get '/utm_campaign_values/:id/against/:other_id', to: redirect('/campaigns/trump/ad_codes/%{id}/against/%{other_id}/')
  get '/utm_campaign_values/:id/hosts', to: redirect('/campaigns/trump/ad_codes/%{id}/hosts')

  resources :hosts, only: :index do
    get 'adverts'
  end
end

app/models/advert.rb
class Advert < ActiveRecord::Base
  TEXT_SEARCH_COLUMNS = %i[external_text ad_creative_body].freeze

  scope :q, lambda { |terms|
    terms = terms.strip.squish
    where("text_search @@ plainto_tsquery('english', ?)", terms)
  }

  trigger.after(:update).of(:external_text, :ad_creative_body) do
    <<~SQL
      UPDATE adverts SET text_search = to_tsvector(external_text || ' ' || ad_creative_body)
      WHERE id = NEW.id
    SQL
  end

  has_many :ad_code_value_usages, -> { order(:index) }
  belongs_to :host
  belongs_to :funded_by, class_name: 'FundingEntity', foreign_key: 'funding_entity_id'

  validates_presence_of :page_name, :funding_entity, :ad_snapshot_url

  FUNDING_ENTITIES_TRUMP = [
    'TRUMP MAKE AMERICA GREAT AGAIN COMMITTEE',
    'DONALD J. TRUMP FOR PRESIDENT, INC.'
  ].freeze

  FUNDING_ENTITIES_BIDEN = [
    'BIDEN FOR PRESIDENT',
    'BIDEN VICTORY FUND',
    'Biden for President'
  ].freeze

  scope :trump, -> { where('adverts.funding_entity IN (?)', FUNDING_ENTITIES_TRUMP) }
  scope :biden, -> { where('adverts.funding_entity IN (?)', FUNDING_ENTITIES_BIDEN) }
  scope :trump_or_biden, -> { where('adverts.funding_entity IN (?)', FUNDING_ENTITIES_BIDEN + FUNDING_ENTITIES_TRUMP) }

  scope :recent, lambda {
    order(ad_creation_time: :desc)
  }

  scope :unpopulated,  -> { where(external_url: nil) }
  scope :populated,    -> { where('adverts.external_url IS NOT NULL') }
  scope :post_scraped, -> { where('adverts.host_id IS NOT NULL') }

  scope :has_utm_campaign_query_param, lambda {
    where("adverts.external_url ~ '\\?.*utm_campaign'")
  }

  scope :has_source_query_param, lambda {
    where("adverts.external_url ~ '[&?]source='")
  }

  scope :needs_ad_code_value_usages, lambda {
    left_joins(:ad_code_value_usages).where('ad_code_value_usages.index IS NULL')
  }

  scope :has_ad_code_value_usages, lambda {
    where('EXISTS(SELECT 1 from ad_code_value_usages where ad_code_value_usages.advert_id = adverts.id)')
  }

  ##
  # Call example: Advert.with_utm_values('0' => 'value', '1' => 'value2')
  scope :with_utm_values, lambda { |hash|
    where('utm_values @> ?', hash.to_json)
  }

  scope :with_hosts, lambda {
    select('hosts.*, MIN(adverts.ad_creation_time) AS ad_first, '\
           'MAX(adverts.ad_creation_time) AS ad_last, COUNT(adverts.id) AS ad_count')
      .joins(:host)
      .group('hosts.id')
  }

  scope :hostname, lambda { |hostname|
    joins(:host).where('hosts.hostname = ?', hostname)
  }

  def self.find_by_c14n_external_url(external_url)
    Advert.find_by(external_url: canonicalize(external_url))
  end

  def self.canonicalize(external_url)
    external_url.sub(/&fbclid=.*[^&]/, '')
  end

  def fb_ad_id
    post_id
  end

  def to_param
    fb_ad_id
  end

  def civil?
    illuminate_tags.fetch('is_civil')
  end

  def uncivil?
    !civil?
  end

  def persuasive?
    illuminate_tags && (
      illuminate_tags['is_message_type_advocacy'] || illuminate_tags['is_message_type_attack']
    )
  end
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  include AdvertsController::Breadcrumbs

  has_scope :with_utm_values, type: :hash
  has_scope :hostname
  has_scope :q

  def index
    @adverts = apply_scopes(Advert.post_scraped)
               .order(ad_creation_time: :desc)
               .page(params[:page])

    @campaign = @adverts&.first&.funded_by&.campaign
    @hosts = apply_scopes(Advert).with_hosts

    add_breadcrumbs_for_campaign_ad_codes!
    add_breadcrumbs_for_scopes!
  end

  def show
    @advert = Advert.find_by!(post_id: params[:id])
    @campaign = @advert.funded_by.campaign
    @ad_codes = AdCode.where(campaign: @campaign).group_by(&:index)

    add_breadcrumbs_for_campaign_ad_codes!
    breadcrumb 'Advert', request.path
  end

  def decode_a_link; end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
  def badge_class(value)
    "badge badge-#{value == '<empty>' ? 'secondary' : 'primary'}"
  end
end

app/views/adverts/_adverts_table.html.erb
<h2><%= page_entries_info @adverts %></h2>

<%= paginate @adverts %>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col" class="external_url" width="20%">Show</th>
      <th scope="col" width="65%">External Advert</th>
      <th scope="col" width="15%">Ad creation time</th>
    </tr>
  </thead>
  <tbody>
  <% @adverts.each do |advert| %>
    <tr>
      <td class="url">
        <div class="btn-group-sm">
          <%= link_to 'Decoded', decoding_path(advert), class: 'btn btn-outline-info' %>
          <%= link_to 'Raw', advert_path(advert), class: 'btn btn-outline-primary' %>
        </div>
      </td>
      <td><%= link_to (advert.ad_creative_body || advert.ad_creative_link_title), advert.external_url %></td>
      <td><%= advert.ad_creation_time %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @adverts %>

app/views/adverts/_decode_a_link_card.html.erb
<div class="decode-a-link card mb-4">
  <div class="card-body">
    <h1>Decode an ad from a Presidential candidate</h1>

    <ol>
      <li>
        For any Facebook ad paid for by the Trump or Biden campaigns, copy:
        <ul>
          <li>The link in any Trump or Biden ad you see on Facebook</li>
          <li>Any link to a Trump or Biden ad in the Facebook Ad Library</li>
          <li>Any Facebook Ad Library ID</li>
        </ul>
      <li>Paste it in the text box below and click "Decode it!"</li>
    </ol>

    <%= form_with url: decodings_path do |form| %>
      <%= form.label t('forms.paste_a_link'), for: :link, class: 'lead' %>
      <div class="decoding form-group form-inline">
        <%= form.text_field :link, class: 'form-control col' %>
        <%= form.submit t('forms.decode_it'), class: 'btn btn-primary ml-2' %>
      </div>
    <% end %>
  </div>
</div>

app/views/adverts/_iframe_info.html.erb
<div class="iframe-info text-muted font-weight-lighter mt-2">
  <p class="h6">
    Has the ad below not loaded?
  </p>
  <p>
    To see Facebook ads here, use an extension like
    <a href="https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe">
      Ignore X-Frame Headers
    </a>.
  </p>
</div>

<iframe src="<%= src %>"></iframe>

app/views/adverts/decode_a_link.html.erb
<%= render 'shared/flash' %>

<%= render 'decode_a_link_card' %>

app/views/adverts/index.html.erb
<% content_for :title, 'Adverts' %>

<%= render 'shared/breadcrumb' %>

<%= render 'hosts/hosts_table' do |host| %>
  <%= link_to "#{host.ad_count} adverts", request.query_parameters.merge(hostname: host.hostname) %>
<% end %>

<%= render 'adverts/adverts_table' %>

app/views/adverts/show.html.erb
<% content_for(:title, "#{@campaign.surname} | #{@advert.ad_creative_link_title}") %>
<h1><%= @advert.ad_creative_link_title %></h1>

<%= render 'shared/breadcrumb' %>

<dl class="metadata">
  <dt>Page</dt>
  <dd><%= @advert.page_name %></dd>
  <dt>Funding entity</dt>
  <dd><%= @advert.funding_entity %></dd>
  <dt>Ad creation time</dt>
  <dd><%= @advert.ad_creation_time %></dd>
  <dt>Ad start date</dt>
  <dd><%= @advert.ad_delivery_start_time %></dd>
  <% if @advert.ad_delivery_stop_time %>
    <dt>Ad stop date</dt>
    <dd><%= @advert.ad_delivery_stop_time %></dd>
  <% end %>
</dl>

<dl class="utm">
  <% @advert.ad_code_value_usages.each do |usage|
    ad_code = @ad_codes[usage.index].first
  %>
    <dt>
      <%= link_to campaign_ad_code_path(campaign_id: @advert.funded_by.campaign, id: usage.index) do %>
        <%= ad_code.name %>
        <small class="text-muted">utm<%= ad_code.index %></small>
      <% end %>
    </dt>
    <dd>
      <%= link_to usage.value,
        campaign_ad_code_value_path(@advert.funded_by.campaign, ad_code.index, usage.value),
        class: badge_class(usage.value)
      %>
    </dd>
  <% end %>
</dl>

<div class="container-fluid previews">
  <div class="row no-gutters">
    <div class="col">
      <%= link_to @advert.ad_snapshot_url, class: 'btn btn-outline-primary mb-2', target: '_blank' do %>
        Open snapshot <small>in new tab</small>
      <% end %>
      <br>
      <%= render 'iframe_info', src: @advert.ad_snapshot_url %>
    </div>

    <div class="col">
      <%= link_to @advert.ad_library_url, class: 'btn btn-outline-secondary mb-2', target: '_blank' do %>
        Open Facebook ad library <small>in new tab</small>
      <% end %>
      <br>
      <%= render 'iframe_info', src:  @advert.ad_library_url %>
    </div>
  </div>
</div>