config/routes.rb
Rails.application.routes.draw do
  root to: 'campaigns#index'

  resources :campaigns, only: %i[index show] do
    resources :ad_codes, only: %i[show index] do
      get 'against/:other_index', to: 'ad_codes#against', as: :against
      get 'hosts'
      get 'timeline'

      resources :values, only: :show
    end
  end

  get '/adverts/decode-a-link'
  resources :adverts, only: %i[show index]

  resources :decodings, only: %i[create show]

  resources :searches, only: %i[new create]

  ##
  # Redirects; this once only did one campaign - Trump's, and now
  # we must preserve URLs in spreadsheets and so on.
  get '/utm_campaign_values', to: redirect('/campaigns/trump/ad_codes')
  get '/utm_campaign_values/:id', to: redirect('/campaigns/trump/ad_codes/%{id}')
  # Between is now default view, or timeline, on ad_codes. Use path: to preserve query string
  get '/utm_campaign_values/:id/between', to: redirect(path: '/campaigns/trump/ad_codes/%{id}')
  get '/utm_campaign_values/:id/against/:other_id', to: redirect('/campaigns/trump/ad_codes/%{id}/against/%{other_id}/')
  get '/utm_campaign_values/:id/hosts', to: redirect('/campaigns/trump/ad_codes/%{id}/hosts')

  resources :hosts, only: :index do
    get 'adverts'
  end
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  include ChartkickGrouping

  has_many :funding_entities
  has_many :hosts
  has_many :ad_codes
  has_many :ad_code_value_summaries # Materialized view model
  has_many :campaign_daily_summaries

  scope :with_summaries, lambda {
    select('campaigns.*, SUM(count) AS ad_count, MIN(campaign_daily_summaries.start) AS ad_oldest')
      .joins(:campaign_daily_summaries)
      .group(:id)
  }

  scope :since, ->(date) { where('campaign_daily_summaries.start > ?', date) }

  def to_param
    slug
  end

  def surname
    slug.capitalize
  end

  def self.summary_graph_data(from:, to: Date.today, dimension: 'count')
    sql = <<~SQL
      SELECT * FROM campaign_daily_summaries WHERE start BETWEEN $1 AND $2
    SQL

    result = ActiveRecord::Base.connection.exec_query(
      sql, 'sql',
      [[nil, from.strftime('%Y-%m-%d')], [nil, to.strftime('%Y-%m-%d')]]
    )

    group_for_chartkick(result, by: 'name', dimension: dimension)
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  ADS_SINCE = '2020-07-01'.freeze

  def index
    @ads_since = Date.parse(ADS_SINCE)
    @campaigns = Campaign.with_summaries.order(:id)
    @ad_counts = Campaign.summary_graph_data(from: @ads_since, dimension: dimension)
    @funding_entity_count = FundingEntity.count
  end

  def show
    @campaign = Campaign.find_by!(slug: params[:id])
    @dimension = dimension
    @wants_summary = WantsDailySummary.send(range, params[:id], dimension: dimension)

    breadcrumb @campaign.name, :current
  end

  private

  def range
    if CampaignsHelper::CAMPAIGN_RANGES.include?(params[:range])
      params[:range]
    else
      'weekly'
    end
  end

  def dimension
    params[:dimension].presence || 'count'
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def advert_count_text
    "#{number_with_delimiter(@campaigns.map(&:ad_count).reduce(&:+))} adverts"
  end

  def campaign_face(slug, options = {})
    image_tag(
      asset_path("face-circle-#{slug}-700x700.png"),
      class: "face img-fluid #{slug} " + options[:class].to_s
    )
  end

  def dimension_label
    {
      'count' => 'Count',
      'approximate_spend' => 'Spend',
      'percentage' => '% of count'
    }[params[:dimension]&.downcase] || 'Count'
  end

  CAMPAIGN_RANGES = %w[
    daily
    weekly
    monthly
  ].freeze

  def campaign_range_links
    tag.ul class: 'nav nav-pills' do
      CAMPAIGN_RANGES.map do |label|
        active = params[:range] == label.to_s || params[:range].nil? && label == 'weekly'
        tag.li class: 'nav-item' do
          link_to label.to_s.titleize,
            request.query_parameters.merge(range: label),
            class: "nav-link #{'active' if active }"
        end
      end.join.html_safe
    end
  end
end

app/views/campaigns/index.html.erb
<h1>Decoding the Presidential candidates’ Facebook advertising</h1>
<%= content_for :title, 'A project by Who Targets Me' %>

<div class="row">
  <div class="col col-lg-8">
  <p class="lead">Modern campaigns run thousands of digital ads at a time.</p>

  <p>Each is a combination of content, targeting and spending designed to provoke the maximum possible reaction from those
    who see it.</p>

  <p>This data investigation, updated daily, shows how the two US Presidential campaigns construct their digital
    advertising and in doing so, shows how they think about their supporters and voters.</p>
  </div>
</div>

<div class="jumbotron campaigns">
  <div class="row">
    <% @campaigns.each do |campaign| %>
      <div class="col-sm-6 campaign campaign-<%= campaign.slug %>">
        <div class="row">
          <div class="col-sm-12 col-md-4">
            <%= link_to campaign_ad_codes_path(campaign.slug) do %>
              <%= campaign_face(campaign.slug) %>
            <% end %>
          </div>

          <div class="col-sm-12 col-md-8">
            <h3 class="campaign-title text-nowrap"><%= campaign.name %></h3>
            <ul class="funding-entities">
              <% campaign.funding_entities.each do |entity| %>
                <li class="text-muted"><%= entity.name %></li>
              <% end %>
            </ul>

            <p class="lead">Total ads: <%= number_with_delimiter(campaign.ad_count) %></p>
          </div>
        </div>

        <h3 class="h5">Explore</h3>
        <div class="d-flex flex-column flex-md-row justify-content-center">
          <%= link_to "Ad codes", campaign_ad_codes_path(campaign.slug), class: 'btn btn-primary flex-grow-1 mr-md-2 mb-2 mb-md-0' %>
          <%= link_to "Campaign wants", campaign_path(campaign.slug), class: 'btn btn-outline-secondary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="row justify-content-center">
  <p class="analysis-based col-sm-8 text-center text-muted">
    Analysis based on <%= advert_count_text %> from the Biden and Trump campaigns
    since <%= @ads_since.strftime('%B %-d') %>
  </p>
</div>

<h2 class="h3">
  Ad
  <%= render 'shared/dimension_dropdown' %>
  per day
</h2>

<div class="row graph">
  <%=
    line_chart @ad_counts,
      height: '600px', curve: true, download: true,
      colors: %w[blue red]
  %>
</div>

app/views/campaigns/show.html.erb
<%= render 'shared/breadcrumb' %>

<% content_for :title, "#{@campaign.surname} campaign wants" %>
<h1 class="mt-4 mb-4">
  <%= image_tag asset_path("face-circle-#{@campaign.slug}-700x700.png"), class: 'face', size: '50x50' %>
  <%= @campaign.surname %> campaign wants <small class="text-muted">over time</small>
</h1>

<div class="btn-toolbar mt-4 mb-4 ml-1">
  <div class="btn-group mr-4" aria-label="Campaign range">
    <%= campaign_range_links %>
  </div>
  <div class="btn-group" aria-label="Show">
    <button class="btn btn-outline" disabled>Show</button>
    <%= render 'shared/dimension_dropdown', show_percentage: true %>
  </div>
</div>

<div class="row graph">
  <%=
    options = {
      height: '700px',
      download: true,
      stacked: true,
    }

    options.merge!(min:0, max: 100) if @dimension == 'percentage'

    column_chart @wants_summary, options
  %>
</div>