config/routes.rb
Rails.application.routes.draw do
  root to: 'campaigns#index'

  resources :campaigns, only: %i[index show] do
    resources :ad_codes, only: %i[show index] do
      get 'against/:other_index', to: 'ad_codes#against', as: :against
      get 'hosts'
      get 'timeline'

      resources :values, only: :show
    end
  end

  get '/adverts/decode-a-link'
  resources :adverts, only: %i[show index]

  resources :decodings, only: %i[create show]

  resources :searches, only: %i[new create]

  ##
  # Redirects; this once only did one campaign - Trump's, and now
  # we must preserve URLs in spreadsheets and so on.
  get '/utm_campaign_values', to: redirect('/campaigns/trump/ad_codes')
  get '/utm_campaign_values/:id', to: redirect('/campaigns/trump/ad_codes/%{id}')
  # Between is now default view, or timeline, on ad_codes. Use path: to preserve query string
  get '/utm_campaign_values/:id/between', to: redirect(path: '/campaigns/trump/ad_codes/%{id}')
  get '/utm_campaign_values/:id/against/:other_id', to: redirect('/campaigns/trump/ad_codes/%{id}/against/%{other_id}/')
  get '/utm_campaign_values/:id/hosts', to: redirect('/campaigns/trump/ad_codes/%{id}/hosts')

  resources :hosts, only: :index do
    get 'adverts'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      Decoding Trump & Biden
      <%= if content_for?(:title) then ' | ' + yield(:title) end %>
    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= render 'shared/metadata' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('wtm_logo_icon.png'), rel: 'icon', size: '192x192', type: 'image/png' %>
    <%= favicon_link_tag asset_path('wtm_logo_icon.png'), rel: 'apple-touch-icon', size: '192x192', type: 'image/png' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  </head>

  <body>

  <main class="container">
    <nav class="navbar navbar-expand-md navbar-light mb-3">
      <%= link_to campaigns_path, class: 'navbar-brand' do %>
        <%= image_tag asset_path('wtm_logo_2020.png'), size: '50x50' %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <%= nav_item nil, campaign_ad_codes_path('biden') do %>
            Biden <span class="d-md-none d-lg-inline">Ad Codes</span>
          <% end  %>
          <%= nav_item nil, campaign_ad_codes_path('trump') do %>
            Trump <span class="d-md-none d-lg-inline">Ad Codes</span>
          <% end %>
          <%= nav_item nil, hosts_path do %>
            <span class="d-md-none d-lg-inline">Campaign </span>Hosts
          <% end %>
          <%= nav_item nil, new_search_path do %>
            <span class="d-md-none d-lg-inline">Ad </span>Search
          <% end %>
        </ul>
        <ul class="navbar-nav external-cta">
          <%= nav_item 'Decode an ad', adverts_decode_a_link_path, class: 'ml-auto btn btn-outline-primary mr-md-3 decode-an-ad' %>
          <%= nav_item 'Donate', t('site.links.wtm_donate'), class: 'btn wtm-donate' %>
          <%= nav_item 'Download Extension', t('site.links.wtm_download_extension'), class: 'btn download-extension' %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </main>

  <footer class="footer mt-5 p-3 text-center">
    <div class="container">
      Conceptualized and created by <a href="https://whotargets.me" target="_blank">Who Targets Me</a>
      and <a href="https://twitter.com/rgarner">Russell Garner</a>, using data from the Facebook Ad Library
      and the <a href="https://illuminating.ischool.syr.edu/" target="_blank">Illuminating Project at Syracuse University</a>.
      Questions and suggestions to contact (at) whotargets dot me. Contributions to decodings welcome at the
      <a href="https://www.github.com/rgarner/polit-ads">GitHub repo</a>.
    </div>
  </footer>
  </body>
</html>